# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-13 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Series')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Name')),
                ('vendor_code', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Vendor code')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
                ('voltage', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Volatage [V]')),
                ('current', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Current [A]')),
                ('type_current', models.CharField(blank=True, choices=[('AC', 'AC'), ('DC', 'DC')], default='AC', max_length=3, null=True, verbose_name='Type of current')),
                ('power', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Power [kW]')),
                ('temperature_protect', models.CharField(blank=True, choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40')], default=None, max_length=3, null=True, verbose_name='Class of temperature protect')),
                ('force_input', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Power items [numb]')),
                ('discret_input', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Discret items [numb]')),
                ('discret_output', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Discret outputs [numb]')),
                ('analog_input', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Analog items [numb]')),
                ('analog_output', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Analog outputs [numb]')),
                ('temperature_input', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Temperature inputs [numb]')),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Height [mm]')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Widht [mm]')),
                ('depth', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Depth [mm]')),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Area [mm^2]')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Currency')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Category item',
                'verbose_name_plural': 'Category items',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items_images/', verbose_name='Image')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database_item.Item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='ItemManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='Short')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Manufacture item',
                'verbose_name_plural': 'Manufacture items',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database_item.ItemCategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database_item.ItemManufacturer', verbose_name='Manufacture'),
        ),
    ]
